### PR TITLE
Update for 17.15.29.1

### PR DESCRIPTION
**Pull request by smarquespt**

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
@smarquespt change destination branch to `ONLYOFFICE:develop`, not `ONLYOFFICE:master`

**Comment by smarquespt** [comment]
@ShockwaveNN 

Please check if it's ok.

**Comment by trofim24** [comment]
@smarquespt thank you for your contribution.

**Comment by ShockwaveNN** [comment]
@smarquespt BTW this changes will not appear in stable version until 5.1 release.

**Pull request merged**
