### PR TITLE
Adds Occitan dictionary

### PR DESCRIPTION
**Pull request by Mejans**
From Hunspell dictionaries

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Hi, please change base branch to develop, since we only accepts third-party PR's in develop

**Comment by Mejans** [comment]
Hello @ShockwaveNN is it better now?

**Comment by ShockwaveNN** [comment]
@Mejans Yeah, branch destination is good.
Could you provide a link to those dictionaries for us to make sure we didn't violate any license issues?

**Comment by Mejans** [comment]
Hello @ShockwaveNN 
I found this: https://github.com/elastic/hunspell/tree/master/dicts/oc_FR
And I've just emailed the original author to make sure it's okay

**Comment by ShockwaveNN** [comment]
@Mejans Yeah, thanks, because I don't see any license in his repo

**Comment by Mejans** [comment]
He answered to say it's okay to use it.

**Comment by ShockwaveNN** [comment]
@Mejans Sorry for the wait, got discussion with dev team )

Could you also add README_oc_FR.txt and license.txt from source repo?

**Comment by ShockwaveNN** [comment]
@Mejans Thanks, I've asked @trofim24 to merge this

**Pull request merged**
