### PR TITLE
add uzbek lang dicts

### PR DESCRIPTION
**Pull request by faxriddin**

### CODE REVIEW

**Review by ShockwaveNN — CHANGES_REQUESTED** [review]
Just got a talk with our dev team and they said that to this works correctly with our code name of directory with language should be the same as name of dic

So

`uz_Cyrl_UZ/uz-Cyrl_UZ.dic`

This should be

`uz_Cyrl_UZ/uz_Cyrl_UZ.dic`

**Comment by ShockwaveNN** [comment]
Thanks, I'll notify our developers and they merge it if everything is ok

**Comment by faxriddin** [comment]
> Thanks, I'll notify our developers and they merge it if everything is ok

Thanks

**Comment by ShockwaveNN** [comment]
Just got a talk

We change the process of using this repo and removed all branches, leaving only `master`

We are very thankful for your job, but seems that we'll be able to merge it only after we make the full release of v7.0.0, somewhere near the end of January
Because if we merge it right now - it will be part of v7.0.0 and we're not prepared for this right now

I'll make a reminder to myself - return to your PR in end of Jan

**Comment by ShockwaveNN** [comment]
@faxriddin Thanks for your contribution )

**Pull request merged**
