### PR TITLE
Update pt_BR dictionary

### PR DESCRIPTION
**Pull request by Lucas-Alf**
The old pt-BR dictionary was suggesting nonsense words.
Example of wrong suggestion:
109239634-a02c2b80-77b4-11eb-917c-5179a106f100

Correct suggestion:
109240319-0bc2c880-77b6-11eb-91b5-cd26046ccfbc

This new dictionary is not perfect, but is better than current.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Could you point out to source of those new dictonaries?

**Comment by Lucas-Alf** [comment]
I found the dictionary on the package sources of Fedora project.
It is made by the same author of the old dictionary: **Raimundo Moura (raimundomoura@openoffice.org)**
https://src.fedoraproject.org/repo/pkgs/hunspell-pt/pt_BR-2011-05-27AOC.zip/606bf3aca8ae8b4f7dfece9164bcf725/

**Comment by ShockwaveNN** [comment]
@Lucas-Alf Ok, thanks, I've asked our dev team if they able to merge it

**Comment by ShockwaveNN** [comment]
Hi again
I've just got a conversation with our dev team
Sorry, they sad that currently we cannot merge your PR because of problem on our code-base side with incorrect support of utf hunspell dictonaries. And merging your PR may cause error similar to https://github.com/ONLYOFFICE/DocumentServer/issues/1033
Also our dev team noted that your PR may work fine on your system, but because of our bug in utf-support in may cause incorrect result only on part of installation base

Our dev team currently are working on complete rewrite of spellcheck module, to make in client-side, not backend side and will this utf problem but this may take a quite a lot time, since it's complete rewrite of spellcheck

**Comment by Lucas-Alf** [comment]
The dictionary from Fedora repository is ANSI.
It made some diference?
Link of dictionary from Fedora repository: https://src.fedoraproject.org/repo/pkgs/hunspell-pt/pt_BR-2011-05-27AOC.zip/606bf3aca8ae8b4f7dfece9164bcf725/

**Comment by ShockwaveNN** [comment]
@Lucas-Alf Seems we are fixed original bug of which we cannot merge your PR earlier, I asked dev team to look at this again, thanks

**Comment by ShockwaveNN** [comment]
@Lucas-Alf Thank you for your contribution

**Pull request merged**
